sudo: required

services:
  - docker

before_install:
  - docker build -t wjatscheslav/multi-container-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run wjatscheslav/multi-container-docker yarn test --coverage

after_success:
  - docker build -t wjatscheslav/multi-client ./client
  - docker build -t wjatscheslav/multi-nginx ./nginx
  - docker build -t wjatscheslav/multi-server ./server
  - docker build -t wjatscheslav/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push wjatscheslav/multi-client
  - docker push wjatscheslav/multi-nginx
  - docker push wjatscheslav/multi-server
  - docker push wjatscheslav/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-527844013357
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY